# This is a basic workflow to help you get started with Actions

name: GetAzureServiceTagsJson

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: GetAzureServiceTagsJson
        run: ./GetAzureServiceTagsJson.ps1
        shell: pwsh

      - name: Commit files
        run: |
          Write-Output "***************************************"
          Write-Output "Performing Git Operations..."
          git config --local user.email "42008359+ryanborMSFT@users.noreply.github.com"
          git config --local user.name "ryanborMSFT"
          Write-Output "Staging all changed files..."
          git add .
          if (git diff HEAD)
          {
              Write-Output "Committing changes..."
              git commit -m "Build Pipeline commit for GetAzureServiceTagsJson [skip ci]"
              Write-Output "Pushing changes to repository..."
              git push -q origin HEAD:main
          }
          else
          {
              "No changes have been made. Skipping Git Push"
          }
          Write-Output "Git Operations Complete..."
          Write-Output "***************************************"
